FROM tomcat:8.0.20-jre8
COPY cloud-apptest.war /usr/local/tomcat/webapps/
ENV DATABASE_URL=jdbc:mysql://us-cdbr-iron-east-04.cleardb.net:3306/ad_d8feb1c22763a0f
ENV DATABASE_USER=b6b57311871e97
ENV DATABASE_PASSWORD=675c96d9
EXPOSE 8080
  